# Generated by Django 3.2.6 on 2021-08-10 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1)),
                ('statuse', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Fail', 'Fail'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('action_date', models.DateField(blank=True, default='', null=True, verbose_name='action date')),
                ('create_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='create date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
